server:
  port: 8080

#connect sql
spring:
  datasource:
    url: ${URL}
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

jwt:
  secret:
    key: ${JWT_KEY}

redis:
  host: localhost
  port: 6379